#!/usr/bin/env python3.6
# -*- coding: utf-8 -*-


"""Snmpttzabbix. 

Usage:
  snmpttozabbix
  snmpttozabbix --verbose
  snmpttozabbix <host> <severity> <key> <value> [--desc=<desc>] [--verbose]

Options:
  -h --help     Show this screen.
  -v --version     Show version.
  --verbose     Show debug info

"""
import sys
import time
import logging
import datetime
from docopt import docopt
from ZabbixSender import ZabbixSender, ZabbixPacket

#Подключаем логи
logfile = '/var/log/snmptt/snmpttozabbix.log'
logger = logging.getLogger(__name__)
handler = logging.FileHandler(logfile)
formatter = logging.Formatter('%(asctime)s %(message)s')
handler.setFormatter(formatter)
logger.addHandler(handler)
logger.setLevel(logging.DEBUG)

def verbose(text):
    if(arguments["--verbose"]) : print(text)
    #print(text)

if __name__ == '__main__':
    arguments = docopt(__doc__, version='Snmpttzabbix 0.1b')
    host = arguments["<host>"]
    key = arguments["<key>"]
    value = arguments["<value>"]

zabbix = ZabbixSender('127.0.0.1', 10051)
packet = ZabbixPacket()

send=True #Разрешает отправку трапа на  zabbix

#Массив строк от snmptrapd
input_raw=sys.stdin.read().split('\n')

#IP адрес хоста отправившего трап
host=input_raw[1].split('[')[1].split(']')[0]
#Время непрерывной работы хоста приславшего трап
d, h, m, s = input_raw[2].split(' ')[1].split('.')[0].split(':')[:4]
uptime=int(d) * 86400 + int(h) * 3600 + int(m) * 60 + int(s)
#Название события вызвавшего трап
name=input_raw[3].split('::')[-1]
#Получаем ключи которые прилетели с трапом
key={}
for i in range(4, len(input_raw)):
    if (input_raw[i]!=""):
        #создаем словарь ключ : значение
        key[input_raw[i].split('::')[1].split(' ')[0]]=input_raw[i].split(' ')[-1]


#Конвеер из правил для отправки в заббикс по заданным ниже шаблонам
linkfilter=["linkDown", "linkUp"]
only_key=["authenticationFailure"]
if(uptime):packet.add(host, "uptime", uptime)
if(name in linkfilter):
    for k,v in key.items():
        packet.add(host, "{0}.[{1}]".format(k.split('.')[0],k.split('.')[1]), v)
elif(name in only_key):
    packet.add(host, name, True)
else:
    logger.debug("Ключ {0!r} неизвестен, необходимо определить для него модель поведения в конвеере правил.".format(name))
    send=False

#Отправляем данные на сервер
if(send): zabbix.send(packet)
verbose(packet.packet)
verbose(zabbix.status)
#logger.debug("Закончил работу")
